### ISSUE TITLE
Bug: can't access secrets from lambda handler

### ISSUE THREAD

**Issue by akumlehn** [mbonig/rds-tools#187]
## bug description

To connect to the rds database, the handler accesses a secret to obtain username and password for the db connection. The secret is read from `SecretsManager`, which is [initialized](https://github.com/mbonig/rds-tools/blob/main/src/handlers/index.ts#L50) to connect to the `us-east-1` region (hard-coded).

## expected behavior

The `SecretsManager` client is configured to the region of the specified secret, and can access it.

## current behavior

For secrets outside of `us-east-1`, the code produces a not found error and the lambda fails.

## reproduce

Setup library in an arbitrary region that is not `us-east-1`, e.g. `eu-central-1`.

## possible solution

The handler code knows the [arn of the secret](https://github.com/mbonig/rds-tools/blob/main/src/handlers/index.ts#L52), which contains it's region. We can extract the region, and initialize the SecretsManager client accordingly.

## other

I would be happy to implement a PR to address this bug :-)

**Comment by akumlehn** [comment]
Possible solution, based on [aws-sdk/util-arn-parser](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_util_arn_parser.html)

```typescript
import * as arn_parse from '@aws-sdk/util-arn-parser';


const arn = arn_parse.parse(
  'arn:aws:secretsmanager:eu-central-1:111111111111:secret:some-rds-secret',
);

console.log(arn.region);
```

**Comment by mbonig** [comment]
I removed the region configuration value from the AWS.SecretsManager constructor. This should resolve the issue. Please re-open if it does not.
